>>> throw Exception("hi there")
java.lang.Exception: hi there
	at Line_0.<init>(Line_0.kts:1)
>>> fun foo() = 2
>>> foo()
2
>>> fun bar(): Nothing = throw AssertionError()
>>> bar()
java.lang.AssertionError
	at Line_3.bar(Line_3.kts:1)
	at Line_4.<init>(Line_4.kts:1)
